# Generated by Django 3.2.8 on 2021-10-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(choices=[('EM', 'בחר אפשררות'), ('CO', 'קבועות'), ('AC', 'רכש'), ('PR', 'ספקים')], default='EM', max_length=2)),
                ('providerName', models.CharField(max_length=100)),
                ('total', models.FloatField()),
                ('isApprove', models.CharField(choices=[('YE', 'כן'), ('NO', 'לא')], default='NO', max_length=2)),
            ],
        ),
    ]
