# Generated by Django 3.2.8 on 2021-10-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalorders',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ApprovedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoiceNumber', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('paidHow', models.CharField(choices=[('BT', 'העברה בנקאית - ירוק'), ('DR', 'דיירקט עידן - צהוב'), ('CC', 'אשראי אופיר - כתום'), ('CH', "צ'ק נייר - אדום"), ('CA', 'מזומן - כחול')], max_length=2)),
                ('whenToPay', models.DateField()),
                ('invoiceLocation', models.CharField(choices=[('PC', 'מסמך בתקייה במחשב - ירוק'), ('PH', 'קובץ נייר במגירה - צהוב'), ('DL', 'במשלוח פיזי למשרד - כתום'), ('EM', 'אין חשבונית - אדום')], max_length=2)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.generalorders')),
            ],
        ),
    ]
