# Generated by Django 3.2.8 on 2021-10-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211007_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedorders',
            name='whenToPay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
