# Generated by Django 3.2.8 on 2021-10-08 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211007_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalorders',
            name='modified',
        ),
    ]
