# Generated by Django 3.2.8 on 2021-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_generalorders_modified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedorders',
            name='parent',
        ),
        migrations.AddField(
            model_name='approvedorders',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='approvedorders',
            name='isApprove',
            field=models.CharField(choices=[('YE', 'כן')], default='YE', max_length=2),
        ),
        migrations.AddField(
            model_name='approvedorders',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='approvedorders',
            name='name',
            field=models.CharField(default='unset name', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedorders',
            name='providerName',
            field=models.CharField(default='unset provider', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='approvedorders',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvedorders',
            name='type',
            field=models.CharField(choices=[('EM', 'בחר אפשררות'), ('CO', 'קבועות'), ('AC', 'רכש'), ('PR', 'ספקים')], default='EM', max_length=2),
        ),
    ]
