# Generated by Django 3.2.8 on 2021-10-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20211008_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedorders',
            name='created',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='approvedorders',
            name='invoiceLocation',
            field=models.CharField(choices=[('PC', 'מסמך בתקייה במחשב - ירוק'), ('PH', 'קובץ נייר במגירה - צהוב'), ('DL', 'במשלוח פיזי למשרד - כתום'), ('EM', 'אין חשבונית - אדום')], default='EM', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvedorders',
            name='isApprove',
            field=models.CharField(choices=[('כן', 'כן')], default='כן', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvedorders',
            name='paidHow',
            field=models.CharField(choices=[('לא שולם', 'לא שולם'), ('העברה בנקאית', 'העברה בנקאית - ירוק'), ('דיירקט עידן', 'דיירקט עידן - צהוב'), ('אשראי אופיר', 'אשראי אופיר - כתום'), ("צ'ק נייר", "צ'ק נייר - אדום"), ('מזומן', 'מזומן - כחול')], default='לא שולם', max_length=50),
        ),
        migrations.AlterField(
            model_name='approvedorders',
            name='type',
            field=models.CharField(choices=[('ריק', 'בחר אפשררות'), ('קבועות', 'קבועות'), ('רכש', 'רכש'), ('ספקים', 'ספקים')], default='EM', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalorders',
            name='isApprove',
            field=models.CharField(choices=[('כן', 'כן'), ('לא', 'לא')], default='לא', max_length=50),
        ),
        migrations.AlterField(
            model_name='generalorders',
            name='type',
            field=models.CharField(choices=[('ריק', 'בחר אפשררות'), ('קבועות', 'קבועות'), ('רכש', 'רכש'), ('ספקים', 'ספקים')], default='EM', max_length=50),
        ),
    ]
