# Generated by Django 3.2.8 on 2021-10-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211011_0915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedorders',
            name='isApprove',
        ),
        migrations.RemoveField(
            model_name='generalorders',
            name='isApprove',
        ),
    ]
