# Generated by Django 3.2.8 on 2021-10-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20211011_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedorders',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
