# Generated by Django 3.2.8 on 2021-10-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_approvedorders_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedorders',
            name='invoiceLocation',
            field=models.CharField(choices=[('מסמך בתקייה במחשב', 'מסמך בתקייה במחשב - ירוק'), ('קובץ נייר במגירה', 'קובץ נייר במגירה - צהוב'), ('במשלוח פיזי למשרד', 'במשלוח פיזי למשרד - כתום'), ('לא ניתן לדיווח', 'לא ניתן לדיווח'), ('אין חשבונית', 'אין חשבונית - אדום')], default='אין חשבונית', max_length=50),
        ),
    ]
