# Generated by Django 3.2.8 on 2021-10-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_approvedorders_invoicelocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250)),
                ('providerName', models.CharField(max_length=100)),
                ('total', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(choices=[('ריק', 'בחר אפשררות'), ('קבועות', 'קבועות'), ('רכש', 'רכש'), ('ספקים', 'ספקים')], default='אין חשבונית', max_length=50)),
                ('invoiceNumber', models.CharField(blank=True, max_length=50)),
                ('paid', models.BooleanField(default=False)),
                ('paidHow', models.CharField(choices=[('לא שולם', 'לא שולם'), ('העברה בנקאית', 'העברה בנקאית - ירוק'), ('דיירקט עידן', 'דיירקט עידן - צהוב'), ('אשראי אופיר', 'אשראי אופיר - כתום'), ("צ'ק נייר", "צ'ק נייר - אדום"), ('מזומן', 'מזומן - כחול')], default='לא שולם', max_length=50)),
                ('whenToPay', models.DateField(blank=True, null=True)),
                ('invoiceLocation', models.CharField(choices=[('מסמך בתקייה במחשב', 'מסמך בתקייה במחשב - ירוק'), ('קובץ נייר במגירה', 'קובץ נייר במגירה - צהוב'), ('במשלוח פיזי למשרד', 'במשלוח פיזי למשרד - כתום'), ('לא ניתן לדיווח', 'לא ניתן לדיווח'), ('אין חשבונית', 'אין חשבונית - אדום')], default='אין חשבונית', max_length=50)),
            ],
        ),
    ]
